name: workflow_dispatch  #

on:
  push:

jobs:
  # This workflow contains a single job called "Set-matrix"
  Set-matrix:
    # The type of runner that the job will run on
    runs-on: [self-hosted,Linux]
    steps:
      
      - name: Checkout this repository
        uses: actions/checkout@v3
      - name: Check pwd
        id: test_pwd
        run: |
          echo "current_path=$(pwd)"
          cp -r ../../../../../nextpf-aubist-ci/* ./
          
  build:
    runs-on: [self-hosted]
    continue-on-error: true
    needs: [Set-matrix]
    steps:
      - name: build start
        id: teat_build
        run: |
          echo "current_path=$(pwd)"
          source script/.env
          #python3 script/operation.py -m build -t ubuntu --force-gen-quit -d  release -sudo hgtpass
          # shell: bash

  static_analyze:
    runs-on: [self-hosted]
    needs: [Set-matrix, build] 
    steps:
      - name: Change dir owner to working user
        run: #echo hgtpass | sudo -S chown -R ${USER}:${USER} ${GITHUB_WORKSPACE}
          echo "static_analyze:"

      - name: Check if target was successful and run static_analyze
        id: static_analyze
        run: |
          echo "Target ubuntu build artifacts exist"
          source script/.env
          #python3 script/operation.py -m static_analyze -t ubuntu -sudo hgtpass

  unit_test_vm:
    runs-on: [self-hosted]
    needs: [Set-matrix, build]
    steps:
      - name: Check if target was successful and run unit_test_VM
        run: |
          echo "Target uttest build artifacts exist"
          source script/.env
          #python3 script/operation.py -m unit_test -t ubuntu --force-gen-quit -sudo hgtpass


        
