name: workflow_dispatch  #zdj 工作流调度

on:
  push:

jobs:
  # This workflow contains a single job called "Set-matrix"
  Set-matrix:
    # The type of runner that the job will run on
    runs-on: [self-hosted]    
    # zdj：self-hosted表示不是 GitHub 提供的云服务器，而是你自己搭建或公司内部部署的机器。 如果使用云端的服务器：  runs-on: ubuntu-latest
    #zdj: onpre 在配置 自建 runner（self-hosted runner）标签（labels） 时自己定义的一个 自定义标签,  这个作用还需要理解 Setting.toml文件中有类似onpre，但是不明白如何关联到一起
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Checkout this repository
        uses: actions/checkout@v3
      - name: Check pwd
        id: test_pwd
        run: |
          echo "current_path=$(pwd)"
          cp -r ../../../../../nextpf-aubist-ci ./
          
  build:
    runs-on: [self-hosted]
    continue-on-error: true
    needs: [Set-matrix]
    steps:
      - name: build start
        id: teat_build
        run: |
          echo "current_path=$(pwd)"
          source script/.env
          python3 script/operation.py -m build -t ubuntu --force-gen-quit -sudo hgtpass
          shell: bash




        
