name: workflow_dispatch  #

on:
  push:

jobs:
  # This workflow contains a single job called "Set-matrix"
  Set-matrix:
    # The type of runner that the job will run on
    runs-on: [self-hosted,Linux]
    steps:
      
      - name: Checkout this repository
        uses: actions/checkout@v3
      - name: Check pwd
        id: test_pwd
        run: |
          echo "current_path=$(pwd)"
          cp -r ../../../../../nextpf-aubist-ci/* ./
      - name: Get submodule version from Setting.toml
        id: Set-version
        run: |
          SCRIPT_VERSION=$(python3 submodule_operation.py -m show_version -t script --no-detail)
          COMMON_UTILITIES_VERSION=$(python3 submodule_operation.py -m show_version -t common_utilities --no-detail)
          UNIQUE_UTILITIES_VERSION=$(python3 submodule_operation.py -m show_version -t unique_utilities --no-detail)
          #IMAGE_LIST_VERSION=$(python3 submodule_operation.py -m show_version -t image_list --no-detail)
          echo "script_version=${SCRIPT_VERSION}"
          echo "common_utilities_version=${COMMON_UTILITIES_VERSION}"
          echo "unique_utilities_version=${UNIQUE_UTILITIES_VERSION}"
          #echo "image_list_version=${IMAGE_LIST_VERSION}"
        #shell: bash 
          
          
  build:
    runs-on: [self-hosted]
    continue-on-error: true
    needs: [Set-matrix]
    steps:
      - name: build start
        id: teat_build
        run: |
          echo "current_path=$(pwd)"
          source script/.env
          #python3 script/operation.py -m build -t ubuntu --force-gen-quit -d  release -sudo hgtpass
          # shell: bash

  static_analyze:
    runs-on: [self-hosted]
    needs: [Set-matrix, build] 
    steps:
      - name: Change dir owner to working user
        run: #echo hgtpass | sudo -S chown -R ${USER}:${USER} ${GITHUB_WORKSPACE}
          echo "static_analyze:"

      - name: Check if target was successful and run static_analyze
        id: static_analyze
        run: |
          echo "Target ubuntu build artifacts exist"
          source script/.env
          #python3 script/operation.py -m static_analyze -t ubuntu -sudo hgtpass

  unit_test_vm:
    runs-on: [self-hosted]
    needs: [Set-matrix, build]
    steps:
      - name: Check if target was successful and run unit_test_VM
        run: |
          echo "Target uttest build artifacts exist"
          source script/.env
          #python3 script/operation.py -m unit_test -t ubuntu --force-gen-quit -sudo hgtpass


        
